openapi: 3.0.1
info:
  title: Table Processor API
  description: |
    API for converting HTML tables into a format suitable for parsing by language models.
    
    This API takes HTML table content and processes it to extract structured data in a key-value format
    that can be easily understood by language models.
  version: 1.0.0
  contact:
    name: Ichi Team
servers:
  - url: http://localhost:3000
    description: Local development server
paths:
  /api/v1/tables/process:
    post:
      summary: Process an HTML table
      description: |
        Converts an HTML table into a format suitable for parsing by language models.
        
        The output is a string of key-value pairs, with each row separated by '---'.
      operationId: processTable
      tags:
        - Tables
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - html
              properties:
                html:
                  type: string
                  description: The HTML content of the table to process
                  example: |
                    <table>
                      <thead>
                        <tr>
                          <th>User ID</th>
                          <th>First Name</th>
                          <th>Last Name</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td>100001</td>
                          <td>John</td>
                          <td>Doe</td>
                        </tr>
                      </tbody>
                    </table>
      responses:
        '200':
          description: Table processed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: string
                    description: The processed table in key-value format
                    example: |
                      User ID: 100001
                      First Name: John
                      Last Name: Doe
        '422':
          description: Unprocessable entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: HTML parameter is required
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: An unexpected error occurred 